import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import './globals.css'

import { getGlobalPageData } from '@/data/loaders'
import Header from '@/components/custom/Header'
import Footer from '@/components/custom/Footer'

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const globalData = await getGlobalPageData()
  return (
    <html lang="en">
      <body className={lato.className}>
        <Header data={globalData.header} />
        {children}
        <Footer data={globalData.footer} />
      </body>
    </html>
  )
}
